/* engine/core/stewardship/mail-engine.js */
const { Resend } = require('resend');
require('dotenv').config();

// Initialize Resend with your Vercel API Key
const resend = new Resend(process.env.RESEND_API_KEY);

/**
 * Artemis Voice Engine (Powered by Resend)
 * Transmits system reports, health checks, and high-value seed alerts to the Architect.
 */
async function sendReport(subject, htmlContent, recipient = null) {
  try {
    if (!process.env.RESEND_API_KEY) {
      throw new Error("RESEND_API_KEY is missing. Voice Engine offline.");
    }

    const targetEmail = recipient || process.env.ARCHITECT_EMAIL;

    if (!targetEmail) {
      throw new Error("No target email specified (Missing ARCHITECT_EMAIL).");
    }

    // Send the email via Resend
    const { data, error } = await resend.emails.send({
      // Use onboarding@resend.dev until you verify a custom domain in the Resend dashboard
      from: 'Artemis <onboarding@resend.dev>', 
      to: targetEmail,
      subject: subject,
      html: htmlContent,
    });

    if (error) {
      console.error('❌ Resend API Error:', error.message);
      return false;
    }

    console.log(`✉️ Transmission successful: ${data.id}`);
    return true;

  } catch (error) {
    console.error('❌ Voice Engine Error:', error.message);
    return false;
  }
}

/**
 * Sends a stylized "Nurture Report" for a specific high-value seed
 */
async function sendNurtureReport(seedData, contactInfo) {
  const subject = `🌱 Artemis High-Value Nurture: ${seedData.target.url}`;
  
  const html = `
    <div style="font-family: 'Courier New', monospace; background: #080819; color: #00f2ff; padding: 20px; border: 1px solid #d4af37; border-radius: 8px;">
      <h2 style="color: #d4af37;">High-Value Seed Detected</h2>
      <p><b>Target:</b> <a href="${seedData.target.url}" style="color: #00ff87;">${seedData.target.url}</a></p>
      <p><b>Council Score:</b> <span style="color: #ff3366; font-size: 1.2em; font-weight: bold;">${seedData.nurture_score}/10</span></p>
      <hr style="border-color: rgba(0, 242, 255, 0.3);">
      
      <h3 style="color: #A259FF;">Extracted Contact Info</h3>
      <pre style="background: rgba(0,242,255,0.1); padding: 10px; border-radius: 4px; color: #fff;">${contactInfo}</pre>
      
      <h3 style="color: #00f2ff;">Invention Proposal</h3>
      <p style="color: #e0e0e0;">${seedData.invention_idea}</p>
      
      <br>
      <p style="font-size: 0.8em; color: #666;">Transmission generated by Artemis Batch Controller.</p>
    </div>
  `;

  return await sendReport(subject, html);
}

module.exports = { sendReport, sendNurtureReport };


