/* engine/core/stewardship/blueprints/index.js */
require('dotenv').config();

/**
 * ARTEMIS BLUEPRINTS MODULE
 * Centralized repository of perfected structural concepts, UI patterns,
 * and monetization components generated by the Council.
 */

const Blueprints = {
    /**
     * Performance & Nurture Optimizer
     */
    UXOptimizer: {
        name: "UX Nurture Optimizer",
        version: "1.2",
        apply: (domNode) => {
            if (!domNode) return;
            
            domNode.style.willChange = "transform, opacity";
            domNode.classList.add('artemis-optimized', 'nurture-flow');
            
            // Optional: Add subtle entrance animation
            domNode.style.transition = "all 0.4s cubic-bezier(0.23, 1, 0.32, 1)";
            domNode.style.opacity = "0";
            setTimeout(() => domNode.style.opacity = "1", 10);
            
            console.log(`✦ UXOptimizer applied to: ${domNode.tagName || 'element'}`);
        }
    },

    /**
     * Autonomous Growth & Propagation Engine
     */
    GrowthEngine: {
        name: "Synthetic Growth Engine",
        version: "1.0",
        init: () => {
            console.log("🚀 Growth Engine Initialized — Autonomous re-routing and cross-pollination enabled.");
            // Future: Add logic for viral loops, referral systems, etc.
        },
        activate: () => {
            console.log("🌱 Growth Engine Active");
        }
    },

    /**
     * Universal Payment Gateway — Core Monetization Component
     * Used across hoodie store, agent marketplace, blueprints, etc.
     */
    UniversalPaymentGateway: {
        name: "Artemis Universal Payment Gateway",
        version: "2.1",

        generateHTML: (productName, price, stripeLink, cryptoLink, options = {}) => {
            const {
                accentColor = "#00f2ff",
                goldAccent = "#d4af37",
                showSecurity = true
            } = options;

            return `
                <!-- Artemis Universal Payment Gateway v2.1 -->
                <div class="artemis-checkout-module" style="
                    background: rgba(8, 8, 25, 0.92);
                    border: 1px solid rgba(0, 242, 255, 0.35);
                    border-radius: 20px;
                    padding: 32px 28px;
                    max-width: 420px;
                    text-align: center;
                    box-shadow: 0 10px 40px rgba(0, 242, 255, 0.12);
                    font-family: 'Courier New', monospace;
                    backdrop-filter: blur(12px);
                    margin: 20px auto;
                ">
                    <div style="
                        width: 64px; height: 64px; border-radius: 50%;
                        background: rgba(212, 175, 55, 0.1);
                        border: 3px solid ${goldAccent};
                        margin: 0 auto 20px;
                        display: flex; align-items: center; justify-content: center;
                        font-size: 28px; box-shadow: 0 0 25px rgba(212,175,55,0.5);
                    ">
                        💎
                    </div>

                    <h3 style="color: ${accentColor}; margin: 0 0 8px 0; font-size: 1.5rem; letter-spacing: 2px; text-transform: uppercase;">
                        ${productName}
                    </h3>
                    
                    <div style="color: #fff; font-size: 2.4rem; font-weight: bold; margin: 16px 0 28px;">
                        ${price}
                    </div>

                    <div style="display: flex; flex-direction: column; gap: 14px;">
                        <a href="${stripeLink}" target="_blank" style="
                            display: block; padding: 16px; background: linear-gradient(90deg, #00f2ff, #0099ff);
                            color: #000; text-decoration: none; font-weight: bold; border-radius: 12px;
                            text-transform: uppercase; letter-spacing: 1.5px; font-size: 1.05rem;
                            box-shadow: 0 0 25px rgba(0, 242, 255, 0.5); transition: all 0.2s;
                        ">
                            Pay with Stripe (Card)
                        </a>
                        
                        <a href="${cryptoLink}" target="_blank" style="
                            display: block; padding: 16px; background: transparent;
                            color: ${goldAccent}; border: 2px solid ${goldAccent};
                            text-decoration: none; font-weight: bold; border-radius: 12px;
                            text-transform: uppercase; letter-spacing: 1.5px; font-size: 1.05rem;
                            transition: all 0.2s;
                        ">
                            Pay with Crypto
                        </a>
                    </div>

                    ${showSecurity ? `
                    <div style="margin-top: 24px; font-size: 0.78rem; color: #666; letter-spacing: 1px;">
                        🔒 SECURED BY ARTEMIS MATRIX • END-TO-END ENCRYPTED
                    </div>` : ''}
                </div>
            `;
        }
    },

    /**
     * Add new blueprints here following the same pattern
     */
    // Example:
    // BrandIntegrator: { ... },
    // OlympusHoodieStore: { ... }
};

module.exports = Blueprints;
